spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/test
    username: root
    password: green502
# swagger
springdoc:
  swagger-ui:
    path: /swagger.html